Fix bug when AWS account has no alias
If an AWS account has no account alias, this error is thrown
[app.py:375] Traceback (most recent call last):
  File "/var/task/federated_aws_rp/app.py", line 313, in lambda_handler
    roles = get_roles(store['id_token'], store.get('cache', True))
  File "/var/task/federated_aws_rp/utils.py", line 438, in get_roles
    alias = role_map.get(
IndexError: list index out of range

This is because the idtoken_for_roles endpoint returns an alias map with a record for the account and a value of an empty list.